language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jsammut/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jsammut/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-048959193685"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "AWS_SECRET_KEY"
